Removed docs from CI and dependencies from conf.py

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -64,32 +64,32 @@ jobs:
         shell: bash -l {0}
         run: |
           pytest -v --cov=stabilizer_project --cov-report=xml --color=yes stabilizer_project/tests/          
-  docs:
-
-    runs-on: ubuntu-latest
-
-    steps:
-    - uses: actions/checkout@v1
-    - uses: ammaraskar/sphinx-action@master
-      with:
-        docs-folder: "docs/"
-
-    - name: Commit documentation changes
-      run: |
-        git clone https://github.com/nrmanohar/stabilizer_project.git --branch gh-pages --single-branch gh-pages
-        cp -r docs/_build/html/* gh-pages/
-        cd gh-pages
-        touch .nojekyll
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add .
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that.
-        
-    - name: Push changes
-      uses: ad-m/github-push-action@master
-      with:
-        branch: gh-pages
-        directory: gh-pages
-        github_token: ${{ secrets.GITHUB_TOKEN }}
+#  docs:
+#
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#    - uses: actions/checkout@v1
+#    - uses: ammaraskar/sphinx-action@master
+#      with:
+#        docs-folder: "docs/"
+#
+#    - name: Commit documentation changes
+#      run: |
+#        git clone https://github.com/nrmanohar/stabilizer_project.git --branch gh-pages --single-branch gh-pages
+#        cp -r docs/_build/html/* gh-pages/
+#        cd gh-pages
+#        touch .nojekyll
+#        git config --local user.email "action@github.com"
+#        git config --local user.name "GitHub Action"
+#        git add .
+#        git commit -m "Update documentation" -a || true
+#        # The above command will fail if no changes were present, so we ignore
+#        # that.
+#        
+#    - name: Push changes
+#      uses: ad-m/github-push-action@master
+#      with:
+#        branch: gh-pages
+#        directory: gh-pages
+#        github_token: ${{ secrets.GITHUB_TOKEN }}
